export type Hospital = {
  id: string;
  name: string;
  city: string;
  state: string;
  type: "federal" | "state" | "private" | "mission";
};

export const HOSPITALS: Hospital[] = [
  // ── FCT (ABUJA) ──────────────────────────────────────────────────────────
  { id: "fct_01", name: "National Hospital Abuja", city: "Abuja (Central)", state: "FCT (Abuja)", type: "federal" },
  { id: "fct_02", name: "University of Abuja Teaching Hospital", city: "Gwagwalada", state: "FCT (Abuja)", type: "federal" },
  { id: "fct_03", name: "Garki General Hospital", city: "Garki", state: "FCT (Abuja)", type: "state" },
  { id: "fct_04", name: "Asokoro District Hospital", city: "Asokoro", state: "FCT (Abuja)", type: "state" },
  { id: "fct_05", name: "Gwagwalada General Hospital", city: "Gwagwalada", state: "FCT (Abuja)", type: "state" },
  { id: "fct_06", name: "Maitama District Hospital", city: "Maitama", state: "FCT (Abuja)", type: "state" },
  { id: "fct_07", name: "Kubwa General Hospital", city: "Kubwa", state: "FCT (Abuja)", type: "state" },
  { id: "fct_08", name: "Kuje General Hospital", city: "Kuje", state: "FCT (Abuja)", type: "state" },
  { id: "fct_09", name: "Cedarcrest Hospitals", city: "Abuja (Central)", state: "FCT (Abuja)", type: "private" },
  { id: "fct_10", name: "Nisa Premier Hospital", city: "Wuse", state: "FCT (Abuja)", type: "private" },
  { id: "fct_11", name: "Abuja Clinic", city: "Wuse", state: "FCT (Abuja)", type: "private" },
  { id: "fct_12", name: "Reiz Continental Hospital", city: "Abuja (Central)", state: "FCT (Abuja)", type: "private" },
  { id: "fct_13", name: "Borromeo Hospital", city: "Abuja (Central)", state: "FCT (Abuja)", type: "mission" },
  { id: "fct_14", name: "Nigerian Turkish International Hospital", city: "Abuja (Central)", state: "FCT (Abuja)", type: "private" },
  { id: "fct_15", name: "Jabi Lake Medical Centre", city: "Wuse", state: "FCT (Abuja)", type: "private" },
  { id: "fct_16", name: "Turkish Nizamiye Hospital", city: "Jabi", state: "FCT (Abuja)", type: "private" },
  { id: "fct_17", name: "57 Medical Services", city: "Wuse", state: "FCT (Abuja)", type: "private" },
  { id: "fct_18", name: "Wuse General Hospital", city: "Wuse", state: "FCT (Abuja)", type: "state" },
  { id: "fct_19", name: "Lifecross Medical Centre", city: "Garki", state: "FCT (Abuja)", type: "private" },
  { id: "fct_20", name: "Zankli Medical Centre", city: "Maitama", state: "FCT (Abuja)", type: "private" },

  // ── ABIA ─────────────────────────────────────────────────────────────────
  { id: "abi_01", name: "Federal Medical Centre Umuahia", city: "Umuahia", state: "Abia", type: "federal" },
  { id: "abi_02", name: "Abia State University Teaching Hospital", city: "Aba", state: "Abia", type: "state" },
  { id: "abi_03", name: "Abia State Specialist Hospital", city: "Umuahia", state: "Abia", type: "state" },
  { id: "abi_04", name: "General Hospital Aba", city: "Aba", state: "Abia", type: "state" },
  { id: "abi_05", name: "Arochukwu General Hospital", city: "Arochukwu", state: "Abia", type: "state" },
  { id: "abi_06", name: "Bende General Hospital", city: "Bende", state: "Abia", type: "state" },
  { id: "abi_07", name: "Sacred Heart Hospital Ohafia", city: "Ohafia", state: "Abia", type: "mission" },
  { id: "abi_08", name: "Salvation Army Hospital", city: "Aba", state: "Abia", type: "mission" },
  { id: "abi_09", name: "Cottage Hospital Umuahia", city: "Umuahia", state: "Abia", type: "private" },
  { id: "abi_10", name: "Meridian Hospital Aba", city: "Aba", state: "Abia", type: "private" },
  { id: "abi_11", name: "Iheoma Hospital", city: "Umuahia", state: "Abia", type: "private" },
  { id: "abi_12", name: "St. Bridget's Hospital Umuahia", city: "Umuahia", state: "Abia", type: "mission" },
  { id: "abi_13", name: "Palm City Hospital", city: "Umuahia", state: "Abia", type: "private" },
  { id: "abi_14", name: "Aba Memorial Hospital", city: "Aba", state: "Abia", type: "state" },

  // ── ADAMAWA ──────────────────────────────────────────────────────────────
  { id: "ada_01", name: "Federal Medical Centre Yola", city: "Yola", state: "Adamawa", type: "federal" },
  { id: "ada_02", name: "Specialist Hospital Yola", city: "Yola", state: "Adamawa", type: "state" },
  { id: "ada_03", name: "General Hospital Mubi", city: "Mubi", state: "Adamawa", type: "state" },
  { id: "ada_04", name: "General Hospital Numan", city: "Numan", state: "Adamawa", type: "state" },
  { id: "ada_05", name: "General Hospital Ganye", city: "Ganye", state: "Adamawa", type: "state" },
  { id: "ada_06", name: "General Hospital Michika", city: "Michika", state: "Adamawa", type: "state" },
  { id: "ada_07", name: "General Hospital Guyuk", city: "Guyuk", state: "Adamawa", type: "state" },
  { id: "ada_08", name: "General Hospital Gombi", city: "Gombi", state: "Adamawa", type: "state" },
  { id: "ada_09", name: "SUM Church Hospital Numan", city: "Numan", state: "Adamawa", type: "mission" },
  { id: "ada_10", name: "Modibbo Adama University Medical Centre", city: "Yola", state: "Adamawa", type: "state" },
  { id: "ada_11", name: "Jimeta Medical Centre", city: "Jimeta", state: "Adamawa", type: "private" },
  { id: "ada_12", name: "Standard Hospital Mubi", city: "Mubi", state: "Adamawa", type: "private" },
  { id: "ada_13", name: "Mayo Belwa General Hospital", city: "Mayo Belwa", state: "Adamawa", type: "state" },
  { id: "ada_14", name: "Ganye Baptist Hospital", city: "Ganye", state: "Adamawa", type: "mission" },

  // ── AKWA IBOM ─────────────────────────────────────────────────────────────
  { id: "aki_01", name: "University of Uyo Teaching Hospital (UUTH)", city: "Uyo", state: "Akwa Ibom", type: "federal" },
  { id: "aki_02", name: "Ibom Specialist Hospital", city: "Uyo", state: "Akwa Ibom", type: "state" },
  { id: "aki_03", name: "General Hospital Ikot Ekpene", city: "Ikot Ekpene", state: "Akwa Ibom", type: "state" },
  { id: "aki_04", name: "General Hospital Eket", city: "Eket", state: "Akwa Ibom", type: "state" },
  { id: "aki_05", name: "General Hospital Oron", city: "Oron", state: "Akwa Ibom", type: "state" },
  { id: "aki_06", name: "General Hospital Ikot Abasi", city: "Ikot Abasi", state: "Akwa Ibom", type: "state" },
  { id: "aki_07", name: "General Hospital Abak", city: "Abak", state: "Akwa Ibom", type: "state" },
  { id: "aki_08", name: "General Hospital Itu", city: "Itu", state: "Akwa Ibom", type: "state" },
  { id: "aki_09", name: "St. Luke's Hospital Anua", city: "Uyo", state: "Akwa Ibom", type: "mission" },
  { id: "aki_10", name: "Faith Clinic Uyo", city: "Uyo", state: "Akwa Ibom", type: "private" },
  { id: "aki_11", name: "Standard Hospital Uyo", city: "Uyo", state: "Akwa Ibom", type: "private" },
  { id: "aki_12", name: "Etinan General Hospital", city: "Etinan", state: "Akwa Ibom", type: "state" },
  { id: "aki_13", name: "Foundation Hospital Uyo", city: "Uyo", state: "Akwa Ibom", type: "private" },
  { id: "aki_14", name: "Doctors Hospital Uyo", city: "Uyo", state: "Akwa Ibom", type: "private" },

  // ── ANAMBRA ───────────────────────────────────────────────────────────────
  { id: "ana_01", name: "Nnamdi Azikiwe University Teaching Hospital", city: "Nnewi", state: "Anambra", type: "federal" },
  { id: "ana_02", name: "Chukwuemeka Odumegwu Ojukwu University Teaching Hospital", city: "Awka", state: "Anambra", type: "state" },
  { id: "ana_03", name: "General Hospital Onitsha", city: "Onitsha", state: "Anambra", type: "state" },
  { id: "ana_04", name: "General Hospital Ekwulobia", city: "Ekwulobia", state: "Anambra", type: "state" },
  { id: "ana_05", name: "General Hospital Nnewi", city: "Nnewi", state: "Anambra", type: "state" },
  { id: "ana_06", name: "General Hospital Ogidi", city: "Ogidi", state: "Anambra", type: "state" },
  { id: "ana_07", name: "St. Charles Borromeo Hospital Onitsha", city: "Onitsha", state: "Anambra", type: "mission" },
  { id: "ana_08", name: "Iyi-Enu Hospital Ogidi", city: "Ogidi", state: "Anambra", type: "mission" },
  { id: "ana_09", name: "Holy Rosary Hospital Waterside", city: "Onitsha", state: "Anambra", type: "mission" },
  { id: "ana_10", name: "Apex Hospital Awka", city: "Awka", state: "Anambra", type: "private" },
  { id: "ana_11", name: "Unique Memorial Hospital Onitsha", city: "Onitsha", state: "Anambra", type: "private" },
  { id: "ana_12", name: "Clina Lancet Awka", city: "Awka", state: "Anambra", type: "private" },
  { id: "ana_13", name: "Tonimas Specialist Hospital", city: "Nnewi", state: "Anambra", type: "private" },
  { id: "ana_14", name: "Prime Medical Centre Nnewi", city: "Nnewi", state: "Anambra", type: "private" },
  { id: "ana_15", name: "Anambra State Specialist Hospital", city: "Awka", state: "Anambra", type: "state" },

  // ── BAUCHI ────────────────────────────────────────────────────────────────
  { id: "bau_01", name: "Abubakar Tafawa Balewa University Teaching Hospital", city: "Bauchi", state: "Bauchi", type: "federal" },
  { id: "bau_02", name: "Bauchi State Specialist Hospital", city: "Bauchi", state: "Bauchi", type: "state" },
  { id: "bau_03", name: "General Hospital Azare", city: "Azare", state: "Bauchi", type: "state" },
  { id: "bau_04", name: "General Hospital Misau", city: "Misau", state: "Bauchi", type: "state" },
  { id: "bau_05", name: "General Hospital Dass", city: "Dass", state: "Bauchi", type: "state" },
  { id: "bau_06", name: "General Hospital Tafawa Balewa", city: "Tafawa Balewa", state: "Bauchi", type: "state" },
  { id: "bau_07", name: "General Hospital Ningi", city: "Ningi", state: "Bauchi", type: "state" },
  { id: "bau_08", name: "Kafin Madaki General Hospital", city: "Katagum", state: "Bauchi", type: "state" },
  { id: "bau_09", name: "Jama'are General Hospital", city: "Jama'are", state: "Bauchi", type: "state" },
  { id: "bau_10", name: "SDA Hospital Bauchi", city: "Bauchi", state: "Bauchi", type: "mission" },
  { id: "bau_11", name: "Faith Specialist Hospital Bauchi", city: "Bauchi", state: "Bauchi", type: "private" },
  { id: "bau_12", name: "Al-Amin Hospital Bauchi", city: "Bauchi", state: "Bauchi", type: "private" },
  { id: "bau_13", name: "Rilwan Specialist Hospital", city: "Bauchi", state: "Bauchi", type: "private" },

  // ── BAYELSA ───────────────────────────────────────────────────────────────
  { id: "bay_01", name: "Federal Medical Centre Yenagoa", city: "Yenagoa", state: "Bayelsa", type: "federal" },
  { id: "bay_02", name: "Niger Delta University Teaching Hospital", city: "Yenagoa", state: "Bayelsa", type: "state" },
  { id: "bay_03", name: "Diette-Spiff Memorial Hospital", city: "Yenagoa", state: "Bayelsa", type: "state" },
  { id: "bay_04", name: "General Hospital Ogbia", city: "Ogbia", state: "Bayelsa", type: "state" },
  { id: "bay_05", name: "General Hospital Brass", city: "Brass", state: "Bayelsa", type: "state" },
  { id: "bay_06", name: "General Hospital Sagbama", city: "Sagbama", state: "Bayelsa", type: "state" },
  { id: "bay_07", name: "General Hospital Ekeremor", city: "Ekeremor", state: "Bayelsa", type: "state" },
  { id: "bay_08", name: "Nembe General Hospital", city: "Nembe", state: "Bayelsa", type: "state" },
  { id: "bay_09", name: "Gloryland Hospital Yenagoa", city: "Yenagoa", state: "Bayelsa", type: "private" },
  { id: "bay_10", name: "Beulah Medical Services", city: "Yenagoa", state: "Bayelsa", type: "private" },
  { id: "bay_11", name: "Bayelsa Specialist Hospital", city: "Yenagoa", state: "Bayelsa", type: "state" },
  { id: "bay_12", name: "Bayelsa Medical University Hospital", city: "Yenagoa", state: "Bayelsa", type: "state" },
  { id: "bay_13", name: "Bethel Medical Centre Yenagoa", city: "Yenagoa", state: "Bayelsa", type: "private" },

  // ── BENUE ─────────────────────────────────────────────────────────────────
  { id: "ben_01", name: "Benue State University Teaching Hospital", city: "Makurdi", state: "Benue", type: "state" },
  { id: "ben_02", name: "Federal Medical Centre Makurdi", city: "Makurdi", state: "Benue", type: "federal" },
  { id: "ben_03", name: "General Hospital Gboko", city: "Gboko", state: "Benue", type: "state" },
  { id: "ben_04", name: "General Hospital Otukpo", city: "Otukpo", state: "Benue", type: "state" },
  { id: "ben_05", name: "General Hospital Katsina-Ala", city: "Katsina-Ala", state: "Benue", type: "state" },
  { id: "ben_06", name: "General Hospital Vandekya", city: "Vandekya", state: "Benue", type: "state" },
  { id: "ben_07", name: "General Hospital Zaki Biam", city: "Zaki Biam", state: "Benue", type: "state" },
  { id: "ben_08", name: "NKST Hospital Mkar", city: "Gboko", state: "Benue", type: "mission" },
  { id: "ben_09", name: "SDA Hospital Makurdi", city: "Makurdi", state: "Benue", type: "mission" },
  { id: "ben_10", name: "Bridge Hospital Makurdi", city: "Makurdi", state: "Benue", type: "private" },
  { id: "ben_11", name: "Benue State Hospital", city: "Makurdi", state: "Benue", type: "state" },
  { id: "ben_12", name: "Otukpo General Hospital", city: "Otukpo", state: "Benue", type: "state" },
  { id: "ben_13", name: "Living Hope Hospital Makurdi", city: "Makurdi", state: "Benue", type: "private" },

  // ── BORNO ─────────────────────────────────────────────────────────────────
  { id: "bor_01", name: "University of Maiduguri Teaching Hospital (UMTH)", city: "Maiduguri", state: "Borno", type: "federal" },
  { id: "bor_02", name: "State Specialist Hospital Maiduguri", city: "Maiduguri", state: "Borno", type: "state" },
  { id: "bor_03", name: "Federal Neuropsychiatric Hospital Maiduguri", city: "Maiduguri", state: "Borno", type: "federal" },
  { id: "bor_04", name: "General Hospital Biu", city: "Biu", state: "Borno", type: "state" },
  { id: "bor_05", name: "General Hospital Gwoza", city: "Gwoza", state: "Borno", type: "state" },
  { id: "bor_06", name: "General Hospital Dikwa", city: "Dikwa", state: "Borno", type: "state" },
  { id: "bor_07", name: "General Hospital Monguno", city: "Monguno", state: "Borno", type: "state" },
  { id: "bor_08", name: "General Hospital Bama", city: "Bama", state: "Borno", type: "state" },
  { id: "bor_09", name: "General Hospital Konduga", city: "Konduga", state: "Borno", type: "state" },
  { id: "bor_10", name: "Borno State Hospital Maiduguri", city: "Maiduguri", state: "Borno", type: "state" },
  { id: "bor_11", name: "Marie Stopes Clinic Maiduguri", city: "Maiduguri", state: "Borno", type: "private" },
  { id: "bor_12", name: "Al-Kanemi Hospital", city: "Maiduguri", state: "Borno", type: "private" },
  { id: "bor_13", name: "Maiduguri City Hospital", city: "Maiduguri", state: "Borno", type: "private" },

  // ── CROSS RIVER ───────────────────────────────────────────────────────────
  { id: "cro_01", name: "University of Calabar Teaching Hospital (UCTH)", city: "Calabar", state: "Cross River", type: "federal" },
  { id: "cro_02", name: "General Hospital Ogoja", city: "Ogoja", state: "Cross River", type: "state" },
  { id: "cro_03", name: "General Hospital Ikom", city: "Ikom", state: "Cross River", type: "state" },
  { id: "cro_04", name: "General Hospital Obudu", city: "Obudu", state: "Cross River", type: "state" },
  { id: "cro_05", name: "General Hospital Ugep", city: "Ugep", state: "Cross River", type: "state" },
  { id: "cro_06", name: "Calabar General Hospital", city: "Calabar", state: "Cross River", type: "state" },
  { id: "cro_07", name: "St. Joseph Hospital Ogoja", city: "Ogoja", state: "Cross River", type: "mission" },
  { id: "cro_08", name: "Diamond Specialist Hospital Calabar", city: "Calabar", state: "Cross River", type: "private" },
  { id: "cro_09", name: "Faith Mediplex Calabar", city: "Calabar", state: "Cross River", type: "private" },
  { id: "cro_10", name: "General Hospital Obubra", city: "Obubra", state: "Cross River", type: "state" },
  { id: "cro_11", name: "St. Margaret's Hospital Calabar", city: "Calabar", state: "Cross River", type: "mission" },
  { id: "cro_12", name: "General Hospital Yala", city: "Yala", state: "Cross River", type: "state" },
  { id: "cro_13", name: "University of Calabar Medical Centre", city: "Calabar", state: "Cross River", type: "state" },
  { id: "cro_14", name: "Kana Specialist Hospital", city: "Calabar", state: "Cross River", type: "private" },

  // ── DELTA ─────────────────────────────────────────────────────────────────
  { id: "del_01", name: "Federal Medical Centre Asaba", city: "Asaba", state: "Delta", type: "federal" },
  { id: "del_02", name: "Delta State University Teaching Hospital", city: "Oghara", state: "Delta", type: "state" },
  { id: "del_03", name: "Central Hospital Warri", city: "Warri", state: "Delta", type: "state" },
  { id: "del_04", name: "Central Hospital Sapele", city: "Sapele", state: "Delta", type: "state" },
  { id: "del_05", name: "Central Hospital Agbor", city: "Agbor", state: "Delta", type: "state" },
  { id: "del_06", name: "General Hospital Kwale", city: "Kwale", state: "Delta", type: "state" },
  { id: "del_07", name: "General Hospital Ozoro", city: "Ozoro", state: "Delta", type: "state" },
  { id: "del_08", name: "Ughelli General Hospital", city: "Ughelli", state: "Delta", type: "state" },
  { id: "del_09", name: "Effurun General Hospital", city: "Effurun", state: "Delta", type: "state" },
  { id: "del_10", name: "Ibusa General Hospital", city: "Ibusa", state: "Delta", type: "state" },
  { id: "del_11", name: "Prime Hospital Warri", city: "Warri", state: "Delta", type: "private" },
  { id: "del_12", name: "Asaba Specialist Hospital", city: "Asaba", state: "Delta", type: "private" },
  { id: "del_13", name: "Warri Specialist Hospital", city: "Warri", state: "Delta", type: "state" },
  { id: "del_14", name: "Orerokpe General Hospital", city: "Orerokpe", state: "Delta", type: "state" },
  { id: "del_15", name: "Pan-African Medical Centre Warri", city: "Warri", state: "Delta", type: "private" },

  // ── EBONYI ────────────────────────────────────────────────────────────────
  { id: "ebo_01", name: "Alex Ekwueme Federal University Teaching Hospital", city: "Abakaliki", state: "Ebonyi", type: "federal" },
  { id: "ebo_02", name: "Ebonyi State University Teaching Hospital", city: "Abakaliki", state: "Ebonyi", type: "state" },
  { id: "ebo_03", name: "General Hospital Afikpo", city: "Afikpo", state: "Ebonyi", type: "state" },
  { id: "ebo_04", name: "General Hospital Onueke", city: "Onueke", state: "Ebonyi", type: "state" },
  { id: "ebo_05", name: "General Hospital Ezza", city: "Ezza", state: "Ebonyi", type: "state" },
  { id: "ebo_06", name: "Mile Four Hospital Abakaliki", city: "Abakaliki", state: "Ebonyi", type: "mission" },
  { id: "ebo_07", name: "Ebonyi State Specialist Hospital", city: "Abakaliki", state: "Ebonyi", type: "state" },
  { id: "ebo_08", name: "Diamond Hospital Abakaliki", city: "Abakaliki", state: "Ebonyi", type: "private" },
  { id: "ebo_09", name: "Volunteer Hospital Abakaliki", city: "Abakaliki", state: "Ebonyi", type: "private" },
  { id: "ebo_10", name: "General Hospital Ishiagu", city: "Ishiagu", state: "Ebonyi", type: "state" },
  { id: "ebo_11", name: "Baptist Hospital Umuoha", city: "Afikpo", state: "Ebonyi", type: "mission" },
  { id: "ebo_12", name: "Ebonyi Medical Centre", city: "Abakaliki", state: "Ebonyi", type: "private" },
  { id: "ebo_13", name: "Bethesda Hospital Abakaliki", city: "Abakaliki", state: "Ebonyi", type: "mission" },

  // ── EDO ───────────────────────────────────────────────────────────────────
  { id: "edo_01", name: "University of Benin Teaching Hospital (UBTH)", city: "Benin City", state: "Edo", type: "federal" },
  { id: "edo_02", name: "Irrua Specialist Teaching Hospital", city: "Ekpoma", state: "Edo", type: "federal" },
  { id: "edo_03", name: "Central Hospital Benin City", city: "Benin City", state: "Edo", type: "state" },
  { id: "edo_04", name: "Stella Obasanjo Hospital", city: "Benin City", state: "Edo", type: "state" },
  { id: "edo_05", name: "General Hospital Uromi", city: "Uromi", state: "Edo", type: "state" },
  { id: "edo_06", name: "General Hospital Auchi", city: "Auchi", state: "Edo", type: "state" },
  { id: "edo_07", name: "General Hospital Ekpoma", city: "Ekpoma", state: "Edo", type: "state" },
  { id: "edo_08", name: "General Hospital Igueben", city: "Igueben", state: "Edo", type: "state" },
  { id: "edo_09", name: "St. Philomena's Hospital", city: "Benin City", state: "Edo", type: "mission" },
  { id: "edo_10", name: "Holy Cross Hospital Benin City", city: "Benin City", state: "Edo", type: "mission" },
  { id: "edo_11", name: "STOIC Hospital Benin City", city: "Benin City", state: "Edo", type: "private" },
  { id: "edo_12", name: "Evelyn Medical Centre", city: "Benin City", state: "Edo", type: "private" },
  { id: "edo_13", name: "Fugar General Hospital", city: "Fugar", state: "Edo", type: "state" },
  { id: "edo_14", name: "Igbinedion University Teaching Hospital", city: "Okada", state: "Edo", type: "private" },
  { id: "edo_15", name: "Alade Specialist Hospital", city: "Benin City", state: "Edo", type: "private" },

  // ── EKITI ─────────────────────────────────────────────────────────────────
  { id: "eki_01", name: "Ekiti State University Teaching Hospital (EKSUTH)", city: "Ado-Ekiti", state: "Ekiti", type: "state" },
  { id: "eki_02", name: "Federal Teaching Hospital Ido-Ekiti", city: "Ido-Ekiti", state: "Ekiti", type: "federal" },
  { id: "eki_03", name: "General Hospital Ikere-Ekiti", city: "Ikere-Ekiti", state: "Ekiti", type: "state" },
  { id: "eki_04", name: "General Hospital Ijero-Ekiti", city: "Ijero-Ekiti", state: "Ekiti", type: "state" },
  { id: "eki_05", name: "General Hospital Oye-Ekiti", city: "Oye-Ekiti", state: "Ekiti", type: "state" },
  { id: "eki_06", name: "General Hospital Efon-Alaaye", city: "Efon-Alaaye", state: "Ekiti", type: "state" },
  { id: "eki_07", name: "General Hospital Aramoko-Ekiti", city: "Aramoko-Ekiti", state: "Ekiti", type: "state" },
  { id: "eki_08", name: "Afe Babalola University Hospital", city: "Ado-Ekiti", state: "Ekiti", type: "private" },
  { id: "eki_09", name: "Christ Hospital Ado-Ekiti", city: "Ado-Ekiti", state: "Ekiti", type: "mission" },
  { id: "eki_10", name: "Ekiti State Hospital", city: "Ado-Ekiti", state: "Ekiti", type: "state" },
  { id: "eki_11", name: "General Hospital Ilawe-Ekiti", city: "Ilawe-Ekiti", state: "Ekiti", type: "state" },
  { id: "eki_12", name: "St. Luke's Hospital Ado-Ekiti", city: "Ado-Ekiti", state: "Ekiti", type: "mission" },
  { id: "eki_13", name: "Grace Hospital Ado-Ekiti", city: "Ado-Ekiti", state: "Ekiti", type: "private" },

  // ── ENUGU ─────────────────────────────────────────────────────────────────
  { id: "enu_01", name: "University of Nigeria Teaching Hospital (UNTH)", city: "Enugu", state: "Enugu", type: "federal" },
  { id: "enu_02", name: "Enugu State University Teaching Hospital (ESUTH)", city: "Enugu", state: "Enugu", type: "state" },
  { id: "enu_03", name: "Park Lane General Hospital", city: "Enugu", state: "Enugu", type: "state" },
  { id: "enu_04", name: "Nsukka General Hospital", city: "Nsukka", state: "Enugu", type: "state" },
  { id: "enu_05", name: "Awgu General Hospital", city: "Awgu", state: "Enugu", type: "state" },
  { id: "enu_06", name: "9th Mile General Hospital", city: "9th Mile Corner", state: "Enugu", type: "state" },
  { id: "enu_07", name: "Bishop Shanahan Hospital Nsukka", city: "Nsukka", state: "Enugu", type: "mission" },
  { id: "enu_08", name: "Holy Ghost Hospital Enugu", city: "Enugu", state: "Enugu", type: "mission" },
  { id: "enu_09", name: "Mother of Christ Specialist Hospital", city: "Enugu", state: "Enugu", type: "mission" },
  { id: "enu_10", name: "Care & Cure Hospital", city: "Enugu", state: "Enugu", type: "private" },
  { id: "enu_11", name: "Udi General Hospital", city: "Udi", state: "Enugu", type: "state" },
  { id: "enu_12", name: "Prime Care Hospital Enugu", city: "Enugu", state: "Enugu", type: "private" },
  { id: "enu_13", name: "Memfys Hospital", city: "Enugu", state: "Enugu", type: "private" },
  { id: "enu_14", name: "Our Lady of Lourdes Hospital Enugu", city: "Enugu", state: "Enugu", type: "mission" },
  { id: "enu_15", name: "St. Raphael's Hospital Nsukka", city: "Nsukka", state: "Enugu", type: "mission" },

  // ── GOMBE ─────────────────────────────────────────────────────────────────
  { id: "gom_01", name: "Federal Teaching Hospital Gombe", city: "Gombe", state: "Gombe", type: "federal" },
  { id: "gom_02", name: "Specialist Hospital Gombe", city: "Gombe", state: "Gombe", type: "state" },
  { id: "gom_03", name: "General Hospital Kaltungo", city: "Kaltungo", state: "Gombe", type: "state" },
  { id: "gom_04", name: "General Hospital Billiri", city: "Billiri", state: "Gombe", type: "state" },
  { id: "gom_05", name: "General Hospital Nafada", city: "Nafada", state: "Gombe", type: "state" },
  { id: "gom_06", name: "General Hospital Dukku", city: "Dukku", state: "Gombe", type: "state" },
  { id: "gom_07", name: "General Hospital Bajoga", city: "Bajoga", state: "Gombe", type: "state" },
  { id: "gom_08", name: "General Hospital Kumo", city: "Kumo", state: "Gombe", type: "state" },
  { id: "gom_09", name: "Pine Hill Hospital Gombe", city: "Gombe", state: "Gombe", type: "private" },
  { id: "gom_10", name: "Gombe State Hospital", city: "Gombe", state: "Gombe", type: "state" },
  { id: "gom_11", name: "Al-Mujtaba Specialist Hospital", city: "Gombe", state: "Gombe", type: "private" },
  { id: "gom_12", name: "Northeast Specialist Hospital", city: "Gombe", state: "Gombe", type: "private" },

  // ── IMO ───────────────────────────────────────────────────────────────────
  { id: "imo_01", name: "Federal Medical Centre Owerri", city: "Owerri", state: "Imo", type: "federal" },
  { id: "imo_02", name: "Imo State University Teaching Hospital", city: "Orlu", state: "Imo", type: "state" },
  { id: "imo_03", name: "General Hospital Orlu", city: "Orlu", state: "Imo", type: "state" },
  { id: "imo_04", name: "General Hospital Okigwe", city: "Okigwe", state: "Imo", type: "state" },
  { id: "imo_05", name: "General Hospital Oguta", city: "Oguta", state: "Imo", type: "state" },
  { id: "imo_06", name: "Owerri General Hospital", city: "Owerri", state: "Imo", type: "state" },
  { id: "imo_07", name: "Holy Rosary Hospital Emekuku", city: "Owerri", state: "Imo", type: "mission" },
  { id: "imo_08", name: "St. Anthony's Hospital Owerri", city: "Owerri", state: "Imo", type: "mission" },
  { id: "imo_09", name: "Bethesda Hospital Owerri", city: "Owerri", state: "Imo", type: "private" },
  { id: "imo_10", name: "Afor Specialist Hospital Owerri", city: "Owerri", state: "Imo", type: "private" },
  { id: "imo_11", name: "Mbaise General Hospital", city: "Mbaise", state: "Imo", type: "state" },
  { id: "imo_12", name: "Nkwerre General Hospital", city: "Nkwerre", state: "Imo", type: "state" },
  { id: "imo_13", name: "Imo Specialist Hospital Owerri", city: "Owerri", state: "Imo", type: "state" },
  { id: "imo_14", name: "Eastern Medical Centre Owerri", city: "Owerri", state: "Imo", type: "private" },
  { id: "imo_15", name: "New Life Hospital Owerri", city: "Owerri", state: "Imo", type: "private" },

  // ── JIGAWA ────────────────────────────────────────────────────────────────
  { id: "jig_01", name: "Federal Medical Centre Birnin Kudu", city: "Birnin Kudu", state: "Jigawa", type: "federal" },
  { id: "jig_02", name: "Jigawa State Specialist Hospital", city: "Dutse", state: "Jigawa", type: "state" },
  { id: "jig_03", name: "General Hospital Dutse", city: "Dutse", state: "Jigawa", type: "state" },
  { id: "jig_04", name: "General Hospital Hadejia", city: "Hadejia", state: "Jigawa", type: "state" },
  { id: "jig_05", name: "General Hospital Gumel", city: "Gumel", state: "Jigawa", type: "state" },
  { id: "jig_06", name: "General Hospital Kazaure", city: "Kazaure", state: "Jigawa", type: "state" },
  { id: "jig_07", name: "General Hospital Ringim", city: "Ringim", state: "Jigawa", type: "state" },
  { id: "jig_08", name: "General Hospital Babura", city: "Babura", state: "Jigawa", type: "state" },
  { id: "jig_09", name: "General Hospital Guri", city: "Guri", state: "Jigawa", type: "state" },
  { id: "jig_10", name: "Hasiya Bayero Hospital Birnin Kudu", city: "Birnin Kudu", state: "Jigawa", type: "state" },
  { id: "jig_11", name: "Dutse Medical Centre", city: "Dutse", state: "Jigawa", type: "private" },
  { id: "jig_12", name: "General Hospital Kiyawa", city: "Kiyawa", state: "Jigawa", type: "state" },
  { id: "jig_13", name: "Jigawa Medical Centre", city: "Dutse", state: "Jigawa", type: "private" },

  // ── KADUNA ────────────────────────────────────────────────────────────────
  { id: "kad_01", name: "Ahmadu Bello University Teaching Hospital (ABUTH)", city: "Zaria", state: "Kaduna", type: "federal" },
  { id: "kad_02", name: "Barau Dikko Teaching Hospital", city: "Kaduna", state: "Kaduna", type: "state" },
  { id: "kad_03", name: "Yusuf Dantsoho Memorial Hospital", city: "Kaduna", state: "Kaduna", type: "state" },
  { id: "kad_04", name: "General Hospital Kafanchan", city: "Kafanchan", state: "Kaduna", type: "state" },
  { id: "kad_05", name: "General Hospital Zaria", city: "Zaria", state: "Kaduna", type: "state" },
  { id: "kad_06", name: "St. Gerard's Hospital Kaduna", city: "Kaduna", state: "Kaduna", type: "mission" },
  { id: "kad_07", name: "Kagoro Christian Hospital", city: "Kagoro", state: "Kaduna", type: "mission" },
  { id: "kad_08", name: "Northern Medical Centre Zaria", city: "Zaria", state: "Kaduna", type: "private" },
  { id: "kad_09", name: "Prime Care Medical Centre Kaduna", city: "Kaduna", state: "Kaduna", type: "private" },
  { id: "kad_10", name: "General Hospital Birnin Gwari", city: "Birnin Gwari", state: "Kaduna", type: "state" },
  { id: "kad_11", name: "Zonkwa General Hospital", city: "Zonkwa", state: "Kaduna", type: "state" },
  { id: "kad_12", name: "Liberty Medical Centre Kaduna", city: "Kaduna", state: "Kaduna", type: "private" },
  { id: "kad_13", name: "Hajj Camp Hospital Kaduna", city: "Kaduna", state: "Kaduna", type: "state" },
  { id: "kad_14", name: "International Eye Centre Kaduna", city: "Kaduna", state: "Kaduna", type: "private" },
  { id: "kad_15", name: "St. Patrick's Hospital Kafanchan", city: "Kafanchan", state: "Kaduna", type: "mission" },

  // ── KANO ──────────────────────────────────────────────────────────────────
  { id: "kan_01", name: "Aminu Kano Teaching Hospital (AKTH)", city: "Kano", state: "Kano", type: "federal" },
  { id: "kan_02", name: "Murtala Mohammed Specialist Hospital", city: "Kano", state: "Kano", type: "state" },
  { id: "kan_03", name: "Muhammad Abdullahi Wase Specialist Hospital", city: "Kano", state: "Kano", type: "state" },
  { id: "kan_04", name: "Hasiya Bayero Paediatric Hospital", city: "Kano", state: "Kano", type: "state" },
  { id: "kan_05", name: "Nasarawa General Hospital Kano", city: "Kano", state: "Kano", type: "state" },
  { id: "kan_06", name: "General Hospital Wudil", city: "Wudil", state: "Kano", type: "state" },
  { id: "kan_07", name: "General Hospital Rano", city: "Rano", state: "Kano", type: "state" },
  { id: "kan_08", name: "General Hospital Bichi", city: "Bichi", state: "Kano", type: "state" },
  { id: "kan_09", name: "General Hospital Gwarzo", city: "Gwarzo", state: "Kano", type: "state" },
  { id: "kan_10", name: "General Hospital Kura", city: "Kura", state: "Kano", type: "state" },
  { id: "kan_11", name: "Hajiya Gambo Sawaba General Hospital", city: "Kano", state: "Kano", type: "state" },
  { id: "kan_12", name: "Doctors Hospital Kano", city: "Kano", state: "Kano", type: "private" },
  { id: "kan_13", name: "City Clinic Kano", city: "Kano", state: "Kano", type: "private" },
  { id: "kan_14", name: "National Orthopaedic Hospital Dala", city: "Dala", state: "Kano", type: "federal" },
  { id: "kan_15", name: "Islamic Medical Centre Kano", city: "Kano", state: "Kano", type: "private" },
  { id: "kan_16", name: "General Hospital Ungogo", city: "Ungogo", state: "Kano", type: "state" },
  { id: "kan_17", name: "Noma Children's Hospital Kano", city: "Kano", state: "Kano", type: "state" },

  // ── KATSINA ───────────────────────────────────────────────────────────────
  { id: "kat_01", name: "Federal Medical Centre Katsina", city: "Katsina", state: "Katsina", type: "federal" },
  { id: "kat_02", name: "Katsina State Specialist Hospital", city: "Katsina", state: "Katsina", type: "state" },
  { id: "kat_03", name: "General Hospital Daura", city: "Daura", state: "Katsina", type: "state" },
  { id: "kat_04", name: "General Hospital Funtua", city: "Funtua", state: "Katsina", type: "state" },
  { id: "kat_05", name: "General Hospital Kankia", city: "Kankia", state: "Katsina", type: "state" },
  { id: "kat_06", name: "General Hospital Malumfashi", city: "Malumfashi", state: "Katsina", type: "state" },
  { id: "kat_07", name: "General Hospital Dutsin-Ma", city: "Dutsin-Ma", state: "Katsina", type: "state" },
  { id: "kat_08", name: "General Hospital Mashi", city: "Mashi", state: "Katsina", type: "state" },
  { id: "kat_09", name: "General Hospital Kaita", city: "Kaita", state: "Katsina", type: "state" },
  { id: "kat_10", name: "General Hospital Jibia", city: "Jibia", state: "Katsina", type: "state" },
  { id: "kat_11", name: "Katsina Medical Centre", city: "Katsina", state: "Katsina", type: "private" },
  { id: "kat_12", name: "Rimi General Hospital", city: "Rimi", state: "Katsina", type: "state" },
  { id: "kat_13", name: "Katsina Children's Hospital", city: "Katsina", state: "Katsina", type: "state" },

  // ── KEBBI ─────────────────────────────────────────────────────────────────
  { id: "keb_01", name: "Federal Medical Centre Birnin Kebbi", city: "Birnin Kebbi", state: "Kebbi", type: "federal" },
  { id: "keb_02", name: "Sir Yahaya Memorial Hospital", city: "Birnin Kebbi", state: "Kebbi", type: "state" },
  { id: "keb_03", name: "General Hospital Argungu", city: "Argungu", state: "Kebbi", type: "state" },
  { id: "keb_04", name: "General Hospital Yauri", city: "Yauri", state: "Kebbi", type: "state" },
  { id: "keb_05", name: "General Hospital Zuru", city: "Zuru", state: "Kebbi", type: "state" },
  { id: "keb_06", name: "General Hospital Koko", city: "Koko", state: "Kebbi", type: "state" },
  { id: "keb_07", name: "General Hospital Bagudo", city: "Bagudo", state: "Kebbi", type: "state" },
  { id: "keb_08", name: "General Hospital Gwandu", city: "Gwandu", state: "Kebbi", type: "state" },
  { id: "keb_09", name: "Birnin Kebbi Specialist Hospital", city: "Birnin Kebbi", state: "Kebbi", type: "state" },
  { id: "keb_10", name: "Excel Medical Centre Birnin Kebbi", city: "Birnin Kebbi", state: "Kebbi", type: "private" },
  { id: "keb_11", name: "General Hospital Kalgo", city: "Kalgo", state: "Kebbi", type: "state" },
  { id: "keb_12", name: "Kebbi State Teaching Hospital", city: "Birnin Kebbi", state: "Kebbi", type: "state" },

  // ── KOGI ──────────────────────────────────────────────────────────────────
  { id: "kog_01", name: "Federal Medical Centre Lokoja", city: "Lokoja", state: "Kogi", type: "federal" },
  { id: "kog_02", name: "Kogi State General Hospital Lokoja", city: "Lokoja", state: "Kogi", type: "state" },
  { id: "kog_03", name: "General Hospital Okene", city: "Okene", state: "Kogi", type: "state" },
  { id: "kog_04", name: "General Hospital Kabba", city: "Kabba", state: "Kogi", type: "state" },
  { id: "kog_05", name: "General Hospital Anyigba", city: "Anyigba", state: "Kogi", type: "state" },
  { id: "kog_06", name: "General Hospital Idah", city: "Idah", state: "Kogi", type: "state" },
  { id: "kog_07", name: "SIM Hospital Egbe", city: "Egbe", state: "Kogi", type: "mission" },
  { id: "kog_08", name: "Holy Family Hospital Kabba", city: "Kabba", state: "Kogi", type: "mission" },
  { id: "kog_09", name: "Sacred Heart Hospital Ajaokuta", city: "Ajaokuta", state: "Kogi", type: "mission" },
  { id: "kog_10", name: "Confluence Medical Centre Lokoja", city: "Lokoja", state: "Kogi", type: "private" },
  { id: "kog_11", name: "General Hospital Ogaminana", city: "Ogaminana", state: "Kogi", type: "state" },
  { id: "kog_12", name: "Lokoja Specialist Hospital", city: "Lokoja", state: "Kogi", type: "state" },
  { id: "kog_13", name: "City Hospital Okene", city: "Okene", state: "Kogi", type: "private" },

  // ── KWARA ─────────────────────────────────────────────────────────────────
  { id: "kwa_01", name: "University of Ilorin Teaching Hospital (UITH)", city: "Ilorin", state: "Kwara", type: "federal" },
  { id: "kwa_02", name: "Kwara State Specialist Hospital", city: "Ilorin", state: "Kwara", type: "state" },
  { id: "kwa_03", name: "General Hospital Ilorin", city: "Ilorin", state: "Kwara", type: "state" },
  { id: "kwa_04", name: "General Hospital Offa", city: "Offa", state: "Kwara", type: "state" },
  { id: "kwa_05", name: "General Hospital Omu-Aran", city: "Omu-Aran", state: "Kwara", type: "state" },
  { id: "kwa_06", name: "General Hospital Share", city: "Share", state: "Kwara", type: "state" },
  { id: "kwa_07", name: "General Hospital Patigi", city: "Patigi", state: "Kwara", type: "state" },
  { id: "kwa_08", name: "Sobi Specialist Hospital Ilorin", city: "Ilorin", state: "Kwara", type: "state" },
  { id: "kwa_09", name: "St. Anthony's Hospital Offa", city: "Offa", state: "Kwara", type: "mission" },
  { id: "kwa_10", name: "Medela Hospital Ilorin", city: "Ilorin", state: "Kwara", type: "private" },
  { id: "kwa_11", name: "Tanke Specialist Hospital Ilorin", city: "Ilorin", state: "Kwara", type: "private" },
  { id: "kwa_12", name: "General Hospital Kaiama", city: "Kaiama", state: "Kwara", type: "state" },
  { id: "kwa_13", name: "Bolton White Medical Centre Ilorin", city: "Ilorin", state: "Kwara", type: "private" },

  // ── LAGOS ─────────────────────────────────────────────────────────────────
  { id: "lag_01", name: "Lagos University Teaching Hospital (LUTH)", city: "Yaba", state: "Lagos", type: "federal" },
  { id: "lag_02", name: "National Orthopaedic Hospital Igbobi", city: "Yaba", state: "Lagos", type: "federal" },
  { id: "lag_03", name: "Lagos Island General Hospital", city: "Lagos Island", state: "Lagos", type: "state" },
  { id: "lag_04", name: "Gbagada General Hospital", city: "Gbagada", state: "Lagos", type: "state" },
  { id: "lag_05", name: "Alimosho General Hospital", city: "Alimosho", state: "Lagos", type: "state" },
  { id: "lag_06", name: "Ikorodu General Hospital", city: "Ikorodu", state: "Lagos", type: "state" },
  { id: "lag_07", name: "Epe General Hospital", city: "Epe", state: "Lagos", type: "state" },
  { id: "lag_08", name: "Badagry General Hospital", city: "Badagry", state: "Lagos", type: "state" },
  { id: "lag_09", name: "Massey Street Children's Hospital", city: "Lagos Island", state: "Lagos", type: "state" },
  { id: "lag_10", name: "Harvey Road General Hospital", city: "Yaba", state: "Lagos", type: "state" },
  { id: "lag_11", name: "St. Nicholas Hospital", city: "Lagos Island", state: "Lagos", type: "private" },
  { id: "lag_12", name: "Reddington Hospital", city: "Victoria Island", state: "Lagos", type: "private" },
  { id: "lag_13", name: "Eko Hospital", city: "Ikeja", state: "Lagos", type: "private" },
  { id: "lag_14", name: "Lagoon Hospitals Apapa", city: "Apapa", state: "Lagos", type: "private" },
  { id: "lag_15", name: "First Consultant Medical Centre", city: "Lagos Island", state: "Lagos", type: "private" },
  { id: "lag_16", name: "Westend Hospital", city: "Surulere", state: "Lagos", type: "private" },
  { id: "lag_17", name: "Lekki Specialist Hospital", city: "Lekki", state: "Lagos", type: "private" },
  { id: "lag_18", name: "St. Luke's Hospital", city: "Yaba", state: "Lagos", type: "mission" },
  { id: "lag_19", name: "Doyen Specialist Hospital", city: "Ikeja", state: "Lagos", type: "private" },
  { id: "lag_20", name: "The Nest Hospital", city: "Surulere", state: "Lagos", type: "private" },
  { id: "lag_21", name: "Evercare Hospital Lagos", city: "Lekki", state: "Lagos", type: "private" },
  { id: "lag_22", name: "R Jolad Hospital", city: "Gbagada", state: "Lagos", type: "private" },
  { id: "lag_23", name: "Duchess International Hospital", city: "Ikeja", state: "Lagos", type: "private" },
  { id: "lag_24", name: "Lagoon Hospital Victoria Island", city: "Victoria Island", state: "Lagos", type: "private" },
  { id: "lag_25", name: "Bridge Clinic Lagos", city: "Victoria Island", state: "Lagos", type: "private" },
  { id: "lag_26", name: "Island Maternity Hospital", city: "Lagos Island", state: "Lagos", type: "state" },
  { id: "lag_27", name: "Ikeja General Hospital", city: "Ikeja", state: "Lagos", type: "state" },
  { id: "lag_28", name: "Isolo General Hospital", city: "Isolo", state: "Lagos", type: "state" },

  // ── NASARAWA ──────────────────────────────────────────────────────────────
  { id: "nas_01", name: "Dalhatu Araf Specialist Hospital", city: "Lafia", state: "Nasarawa", type: "federal" },
  { id: "nas_02", name: "Federal Medical Centre Keffi", city: "Keffi", state: "Nasarawa", type: "federal" },
  { id: "nas_03", name: "Nasarawa State General Hospital", city: "Lafia", state: "Nasarawa", type: "state" },
  { id: "nas_04", name: "General Hospital Akwanga", city: "Akwanga", state: "Nasarawa", type: "state" },
  { id: "nas_05", name: "General Hospital Nasarawa", city: "Nasarawa", state: "Nasarawa", type: "state" },
  { id: "nas_06", name: "General Hospital Doma", city: "Doma", state: "Nasarawa", type: "state" },
  { id: "nas_07", name: "General Hospital Wamba", city: "Wamba", state: "Nasarawa", type: "state" },
  { id: "nas_08", name: "General Hospital Keffi", city: "Keffi", state: "Nasarawa", type: "state" },
  { id: "nas_09", name: "Lafia Medical Centre", city: "Lafia", state: "Nasarawa", type: "private" },
  { id: "nas_10", name: "Sterling Medical Centre Lafia", city: "Lafia", state: "Nasarawa", type: "private" },
  { id: "nas_11", name: "Nasarawa State University Hospital", city: "Keffi", state: "Nasarawa", type: "state" },
  { id: "nas_12", name: "Nasarawa Medical Centre", city: "Lafia", state: "Nasarawa", type: "private" },

  // ── NIGER ─────────────────────────────────────────────────────────────────
  { id: "nig_01", name: "Ibrahim Badamasi Babangida Specialist Hospital", city: "Minna", state: "Niger", type: "state" },
  { id: "nig_02", name: "Federal Medical Centre Bida", city: "Bida", state: "Niger", type: "federal" },
  { id: "nig_03", name: "General Hospital Suleja", city: "Suleja", state: "Niger", type: "state" },
  { id: "nig_04", name: "General Hospital Kontagora", city: "Kontagora", state: "Niger", type: "state" },
  { id: "nig_05", name: "Minna General Hospital", city: "Minna", state: "Niger", type: "state" },
  { id: "nig_06", name: "General Hospital Lapai", city: "Lapai", state: "Niger", type: "state" },
  { id: "nig_07", name: "General Hospital Kagara", city: "Kagara", state: "Niger", type: "state" },
  { id: "nig_08", name: "General Hospital Mokwa", city: "Mokwa", state: "Niger", type: "state" },
  { id: "nig_09", name: "Bida General Hospital", city: "Bida", state: "Niger", type: "state" },
  { id: "nig_10", name: "Agaie General Hospital", city: "Agaie", state: "Niger", type: "state" },
  { id: "nig_11", name: "Borgu General Hospital", city: "New Bussa", state: "Niger", type: "state" },
  { id: "nig_12", name: "Nupeco Hospital Minna", city: "Minna", state: "Niger", type: "private" },
  { id: "nig_13", name: "Minna Specialist Hospital", city: "Minna", state: "Niger", type: "private" },

  // ── OGUN ──────────────────────────────────────────────────────────────────
  { id: "ogu_01", name: "Federal Medical Centre Abeokuta", city: "Abeokuta", state: "Ogun", type: "federal" },
  { id: "ogu_02", name: "Olabisi Onabanjo University Teaching Hospital (OOUTH)", city: "Sagamu", state: "Ogun", type: "state" },
  { id: "ogu_03", name: "Sacred Heart Hospital Abeokuta", city: "Abeokuta", state: "Ogun", type: "mission" },
  { id: "ogu_04", name: "State Hospital Ijebu-Ode", city: "Ijebu-Ode", state: "Ogun", type: "state" },
  { id: "ogu_05", name: "General Hospital Ilaro", city: "Ilaro", state: "Ogun", type: "state" },
  { id: "ogu_06", name: "General Hospital Ifo", city: "Ifo", state: "Ogun", type: "state" },
  { id: "ogu_07", name: "General Hospital Ota", city: "Ota", state: "Ogun", type: "state" },
  { id: "ogu_08", name: "General Hospital Ogijo", city: "Ogijo", state: "Ogun", type: "state" },
  { id: "ogu_09", name: "Our Lady of Apostles Hospital Ilaro", city: "Ilaro", state: "Ogun", type: "mission" },
  { id: "ogu_10", name: "Regal Medical Centre Abeokuta", city: "Abeokuta", state: "Ogun", type: "private" },
  { id: "ogu_11", name: "Divine Specialist Hospital Sagamu", city: "Sagamu", state: "Ogun", type: "private" },
  { id: "ogu_12", name: "General Hospital Ijebu-Igbo", city: "Ijebu-Igbo", state: "Ogun", type: "state" },
  { id: "ogu_13", name: "Bishop Davidson Hospital Sagamu", city: "Sagamu", state: "Ogun", type: "mission" },
  { id: "ogu_14", name: "General Hospital Agbara", city: "Agbara", state: "Ogun", type: "state" },
  { id: "ogu_15", name: "Remo District Hospital", city: "Sagamu", state: "Ogun", type: "state" },

  // ── ONDO ──────────────────────────────────────────────────────────────────
  { id: "ond_01", name: "Federal Medical Centre Owo", city: "Owo", state: "Ondo", type: "federal" },
  { id: "ond_02", name: "University of Medical Sciences Teaching Hospital", city: "Akure", state: "Ondo", type: "state" },
  { id: "ond_03", name: "Mother & Child Hospital Akure", city: "Akure", state: "Ondo", type: "state" },
  { id: "ond_04", name: "Ondo State Specialist Hospital", city: "Akure", state: "Ondo", type: "state" },
  { id: "ond_05", name: "General Hospital Ondo Town", city: "Ondo", state: "Ondo", type: "state" },
  { id: "ond_06", name: "General Hospital Ikare-Akoko", city: "Ikare-Akoko", state: "Ondo", type: "state" },
  { id: "ond_07", name: "General Hospital Okitipupa", city: "Okitipupa", state: "Ondo", type: "state" },
  { id: "ond_08", name: "General Hospital Ore", city: "Ore", state: "Ondo", type: "state" },
  { id: "ond_09", name: "General Hospital Idanre", city: "Idanre", state: "Ondo", type: "state" },
  { id: "ond_10", name: "Baptist Medical Centre Ogbese", city: "Oba-Ile", state: "Ondo", type: "mission" },
  { id: "ond_11", name: "Specialist Hospital Akure", city: "Akure", state: "Ondo", type: "private" },
  { id: "ond_12", name: "General Hospital Ile-Oluji", city: "Ile-Oluji", state: "Ondo", type: "state" },
  { id: "ond_13", name: "Healing Stripes Hospital Akure", city: "Akure", state: "Ondo", type: "private" },
  { id: "ond_14", name: "General Hospital Irele", city: "Irele", state: "Ondo", type: "state" },

  // ── OSUN ──────────────────────────────────────────────────────────────────
  { id: "osu_01", name: "Obafemi Awolowo University Teaching Hospital (OAUTHC)", city: "Ile-Ife", state: "Osun", type: "federal" },
  { id: "osu_02", name: "LAUTECH Teaching Hospital Osogbo", city: "Osogbo", state: "Osun", type: "state" },
  { id: "osu_03", name: "Osun State General Hospital", city: "Osogbo", state: "Osun", type: "state" },
  { id: "osu_04", name: "General Hospital Ilesa", city: "Ilesa", state: "Osun", type: "state" },
  { id: "osu_05", name: "General Hospital Ede", city: "Ede", state: "Osun", type: "state" },
  { id: "osu_06", name: "General Hospital Iwo", city: "Iwo", state: "Osun", type: "state" },
  { id: "osu_07", name: "Wesley Guild Hospital Ilesa", city: "Ilesa", state: "Osun", type: "mission" },
  { id: "osu_08", name: "General Hospital Inisa", city: "Inisa", state: "Osun", type: "state" },
  { id: "osu_09", name: "Osun State Specialist Hospital", city: "Osogbo", state: "Osun", type: "state" },
  { id: "osu_10", name: "Millennium Hospital Osogbo", city: "Osogbo", state: "Osun", type: "private" },
  { id: "osu_11", name: "General Hospital Ikirun", city: "Ikirun", state: "Osun", type: "state" },
  { id: "osu_12", name: "General Hospital Ejigbo", city: "Ejigbo", state: "Osun", type: "state" },
  { id: "osu_13", name: "Apostolic Faith Hospital Ilesa", city: "Ilesa", state: "Osun", type: "mission" },
  { id: "osu_14", name: "Heritage Hospital Osogbo", city: "Osogbo", state: "Osun", type: "private" },
  { id: "osu_15", name: "Seventh Day Hospital Ile-Ife", city: "Ile-Ife", state: "Osun", type: "mission" },

  // ── OYO ───────────────────────────────────────────────────────────────────
  { id: "oyo_01", name: "University College Hospital (UCH) Ibadan", city: "Ibadan", state: "Oyo", type: "federal" },
  { id: "oyo_02", name: "Ring Road State Hospital Ibadan", city: "Ibadan", state: "Oyo", type: "state" },
  { id: "oyo_03", name: "Adeoyo State Hospital Ibadan", city: "Ibadan", state: "Oyo", type: "state" },
  { id: "oyo_04", name: "Jericho Specialist Hospital Ibadan", city: "Ibadan", state: "Oyo", type: "state" },
  { id: "oyo_05", name: "Oni Memorial Children's Hospital", city: "Ibadan", state: "Oyo", type: "state" },
  { id: "oyo_06", name: "General Hospital Saki", city: "Saki", state: "Oyo", type: "state" },
  { id: "oyo_07", name: "General Hospital Oyo", city: "Oyo", state: "Oyo", type: "state" },
  { id: "oyo_08", name: "Baptist Medical Centre Ogbomosho", city: "Ogbomosho", state: "Oyo", type: "mission" },
  { id: "oyo_09", name: "General Hospital Iseyin", city: "Iseyin", state: "Oyo", type: "state" },
  { id: "oyo_10", name: "Bowen University Teaching Hospital", city: "Ogbomosho", state: "Oyo", type: "mission" },
  { id: "oyo_11", name: "Ibadan Clinic", city: "Ibadan", state: "Oyo", type: "private" },
  { id: "oyo_12", name: "St. Mary's Specialist Hospital Ibadan", city: "Ibadan", state: "Oyo", type: "private" },
  { id: "oyo_13", name: "Ona-Ara General Hospital", city: "Ibadan", state: "Oyo", type: "state" },
  { id: "oyo_14", name: "General Hospital Ogbomosho", city: "Ogbomosho", state: "Oyo", type: "state" },
  { id: "oyo_15", name: "Primus Medical Centre Ibadan", city: "Ibadan", state: "Oyo", type: "private" },
  { id: "oyo_16", name: "Immaculate Heart Hospital Ibadan", city: "Ibadan", state: "Oyo", type: "mission" },
  { id: "oyo_17", name: "Geo Hospital Ibadan", city: "Ibadan", state: "Oyo", type: "private" },
  { id: "oyo_18", name: "LAUTECH Teaching Hospital Ogbomosho", city: "Ogbomosho", state: "Oyo", type: "state" },

  // ── PLATEAU ───────────────────────────────────────────────────────────────
  { id: "pla_01", name: "Jos University Teaching Hospital (JUTH)", city: "Jos", state: "Plateau", type: "federal" },
  { id: "pla_02", name: "Plateau Specialist Hospital", city: "Jos", state: "Plateau", type: "state" },
  { id: "pla_03", name: "Vom Christian Hospital", city: "Vom", state: "Plateau", type: "mission" },
  { id: "pla_04", name: "General Hospital Pankshin", city: "Pankshin", state: "Plateau", type: "state" },
  { id: "pla_05", name: "General Hospital Shendam", city: "Shendam", state: "Plateau", type: "state" },
  { id: "pla_06", name: "General Hospital Langtang", city: "Langtang", state: "Plateau", type: "state" },
  { id: "pla_07", name: "General Hospital Barkin Ladi", city: "Barkin Ladi", state: "Plateau", type: "state" },
  { id: "pla_08", name: "General Hospital Mangu", city: "Mangu", state: "Plateau", type: "state" },
  { id: "pla_09", name: "Evangel Hospital Jos", city: "Jos", state: "Plateau", type: "mission" },
  { id: "pla_10", name: "St. Piran's Hospital Jos", city: "Jos", state: "Plateau", type: "mission" },
  { id: "pla_11", name: "Enos Medical Centre Jos", city: "Jos", state: "Plateau", type: "private" },
  { id: "pla_12", name: "Pine Brook Hospital Jos", city: "Jos", state: "Plateau", type: "private" },
  { id: "pla_13", name: "General Hospital Bukuru", city: "Bukuru", state: "Plateau", type: "state" },
  { id: "pla_14", name: "Bingham University Teaching Hospital", city: "Jos", state: "Plateau", type: "mission" },

  // ── RIVERS ────────────────────────────────────────────────────────────────
  { id: "riv_01", name: "University of Port Harcourt Teaching Hospital (UPTH)", city: "Port Harcourt", state: "Rivers", type: "federal" },
  { id: "riv_02", name: "Braithwaite Memorial Specialist Hospital", city: "Port Harcourt", state: "Rivers", type: "state" },
  { id: "riv_03", name: "Rivers State University Teaching Hospital", city: "Port Harcourt", state: "Rivers", type: "state" },
  { id: "riv_04", name: "General Hospital Bonny", city: "Bonny", state: "Rivers", type: "state" },
  { id: "riv_05", name: "General Hospital Ahoada", city: "Ahoada", state: "Rivers", type: "state" },
  { id: "riv_06", name: "General Hospital Omoku", city: "Omoku", state: "Rivers", type: "state" },
  { id: "riv_07", name: "General Hospital Degema", city: "Degema", state: "Rivers", type: "state" },
  { id: "riv_08", name: "General Hospital Eleme", city: "Eleme", state: "Rivers", type: "state" },
  { id: "riv_09", name: "Kelsey Harrison Hospital", city: "Port Harcourt", state: "Rivers", type: "private" },
  { id: "riv_10", name: "Havana Specialist Hospital", city: "Port Harcourt", state: "Rivers", type: "private" },
  { id: "riv_11", name: "Portmedic Hospital", city: "Port Harcourt", state: "Rivers", type: "private" },
  { id: "riv_12", name: "St. Mary's Hospital Elele", city: "Ahoada", state: "Rivers", type: "mission" },
  { id: "riv_13", name: "Nkpolu General Hospital", city: "Port Harcourt", state: "Rivers", type: "state" },
  { id: "riv_14", name: "Medicare Specialist Hospital", city: "Port Harcourt", state: "Rivers", type: "private" },
  { id: "riv_15", name: "Gold Cross Hospital", city: "Port Harcourt", state: "Rivers", type: "private" },
  { id: "riv_16", name: "Rumuola General Hospital", city: "Port Harcourt", state: "Rivers", type: "state" },
  { id: "riv_17", name: "Obio General Hospital", city: "Port Harcourt", state: "Rivers", type: "state" },

  // ── SOKOTO ────────────────────────────────────────────────────────────────
  { id: "sok_01", name: "Usmanu Danfodiyo University Teaching Hospital", city: "Sokoto", state: "Sokoto", type: "federal" },
  { id: "sok_02", name: "Specialist Hospital Sokoto", city: "Sokoto", state: "Sokoto", type: "state" },
  { id: "sok_03", name: "Maryam Abacha Women and Children Hospital", city: "Sokoto", state: "Sokoto", type: "state" },
  { id: "sok_04", name: "General Hospital Wurno", city: "Wurno", state: "Sokoto", type: "state" },
  { id: "sok_05", name: "General Hospital Rabah", city: "Rabah", state: "Sokoto", type: "state" },
  { id: "sok_06", name: "General Hospital Tambuwal", city: "Tambuwal", state: "Sokoto", type: "state" },
  { id: "sok_07", name: "General Hospital Isa", city: "Isa", state: "Sokoto", type: "state" },
  { id: "sok_08", name: "General Hospital Bodinga", city: "Bodinga", state: "Sokoto", type: "state" },
  { id: "sok_09", name: "Sokoto State General Hospital", city: "Sokoto", state: "Sokoto", type: "state" },
  { id: "sok_10", name: "Modern Hospital Sokoto", city: "Sokoto", state: "Sokoto", type: "private" },
  { id: "sok_11", name: "General Hospital Goronyo", city: "Goronyo", state: "Sokoto", type: "state" },
  { id: "sok_12", name: "Sokoto Specialist Medical Centre", city: "Sokoto", state: "Sokoto", type: "private" },

  // ── TARABA ────────────────────────────────────────────────────────────────
  { id: "tar_01", name: "Federal Medical Centre Jalingo", city: "Jalingo", state: "Taraba", type: "federal" },
  { id: "tar_02", name: "Taraba State Specialist Hospital", city: "Jalingo", state: "Taraba", type: "state" },
  { id: "tar_03", name: "General Hospital Wukari", city: "Wukari", state: "Taraba", type: "state" },
  { id: "tar_04", name: "General Hospital Bali", city: "Bali", state: "Taraba", type: "state" },
  { id: "tar_05", name: "General Hospital Gassol", city: "Gassol", state: "Taraba", type: "state" },
  { id: "tar_06", name: "General Hospital Zing", city: "Zing", state: "Taraba", type: "state" },
  { id: "tar_07", name: "General Hospital Karim Lamido", city: "Karim Lamido", state: "Taraba", type: "state" },
  { id: "tar_08", name: "General Hospital Ibi", city: "Ibi", state: "Taraba", type: "state" },
  { id: "tar_09", name: "SUM Hospital Wukari", city: "Wukari", state: "Taraba", type: "mission" },
  { id: "tar_10", name: "Faith Specialist Hospital Jalingo", city: "Jalingo", state: "Taraba", type: "private" },
  { id: "tar_11", name: "General Hospital Takum", city: "Takum", state: "Taraba", type: "state" },
  { id: "tar_12", name: "Jalingo Medical Centre", city: "Jalingo", state: "Taraba", type: "private" },

  // ── YOBE ──────────────────────────────────────────────────────────────────
  { id: "yob_01", name: "Federal Medical Centre Nguru", city: "Nguru", state: "Yobe", type: "federal" },
  { id: "yob_02", name: "Specialist Hospital Damaturu", city: "Damaturu", state: "Yobe", type: "state" },
  { id: "yob_03", name: "General Hospital Potiskum", city: "Potiskum", state: "Yobe", type: "state" },
  { id: "yob_04", name: "General Hospital Gashua", city: "Gashua", state: "Yobe", type: "state" },
  { id: "yob_05", name: "General Hospital Nguru", city: "Nguru", state: "Yobe", type: "state" },
  { id: "yob_06", name: "General Hospital Nangere", city: "Nangere", state: "Yobe", type: "state" },
  { id: "yob_07", name: "General Hospital Gujba", city: "Gujba", state: "Yobe", type: "state" },
  { id: "yob_08", name: "Yobe State Hospital Damaturu", city: "Damaturu", state: "Yobe", type: "state" },
  { id: "yob_09", name: "General Hospital Bade", city: "Bade", state: "Yobe", type: "state" },
  { id: "yob_10", name: "Prime Medical Centre Damaturu", city: "Damaturu", state: "Yobe", type: "private" },
  { id: "yob_11", name: "General Hospital Geidam", city: "Geidam", state: "Yobe", type: "state" },
  { id: "yob_12", name: "Yobe State University Teaching Hospital", city: "Damaturu", state: "Yobe", type: "state" },

  // ── ZAMFARA ───────────────────────────────────────────────────────────────
  { id: "zam_01", name: "Federal Medical Centre Gusau", city: "Gusau", state: "Zamfara", type: "federal" },
  { id: "zam_02", name: "Yariman Bakura Specialist Hospital", city: "Gusau", state: "Zamfara", type: "state" },
  { id: "zam_03", name: "General Hospital Kaura Namoda", city: "Kaura Namoda", state: "Zamfara", type: "state" },
  { id: "zam_04", name: "General Hospital Anka", city: "Anka", state: "Zamfara", type: "state" },
  { id: "zam_05", name: "General Hospital Talata Mafara", city: "Talata Mafara", state: "Zamfara", type: "state" },
  { id: "zam_06", name: "General Hospital Zurmi", city: "Zurmi", state: "Zamfara", type: "state" },
  { id: "zam_07", name: "General Hospital Maradun", city: "Maradun", state: "Zamfara", type: "state" },
  { id: "zam_08", name: "General Hospital Bungudu", city: "Bungudu", state: "Zamfara", type: "state" },
  { id: "zam_09", name: "Gusau General Hospital", city: "Gusau", state: "Zamfara", type: "state" },
  { id: "zam_10", name: "Life Care Hospital Gusau", city: "Gusau", state: "Zamfara", type: "private" },
  { id: "zam_11", name: "General Hospital Maru", city: "Maru", state: "Zamfara", type: "state" },
  { id: "zam_12", name: "Zamfara Specialist Medical Centre", city: "Gusau", state: "Zamfara", type: "private" },
];

export function getHospitalsByState(state: string): Hospital[] {
  return HOSPITALS.filter(
    (h) => h.state.toLowerCase() === state.toLowerCase()
  );
}

export function getHospitalsByCity(state: string, city: string): Hospital[] {
  return HOSPITALS.filter(
    (h) =>
      h.state.toLowerCase() === state.toLowerCase() &&
      h.city.toLowerCase() === city.toLowerCase()
  );
}

export function getCitiesByState(state: string): string[] {
  const cities = new Set(
    HOSPITALS.filter((h) => h.state.toLowerCase() === state.toLowerCase()).map(
      (h) => h.city
    )
  );
  return Array.from(cities).sort();
}
